# Generated by Django 4.1.7 on 2023-03-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_payment_amount_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
