# Generated by Django 4.1.7 on 2023-03-17 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_payment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
