# Generated by Django 4.1.1 on 2023-07-30 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_payment_created_at_payment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
